### ISSUE TITLE
LESS parser outputs .less instead of .css

### ISSUE THREAD

**Issue by jmcgaha** [benwilkins/AutoMin#10]
I've got everything working on the new version but when I use the less tag it successfully parses the less files and correctly makes one new file. The only problem is that file is a .less file and not a .css file, so the browser refuses to use it to style the page.

Here is my template (I added the spaces around the < > to make it show up here):
{exp:automin:less attribute:type="text/css" attribute:rel="stylesheet"}
    < link rel="stylesheet/less" type="text/css" href="/less/bootstrap.less" >
{/exp:automin:less}

Here is the output:
< link href="/automin/8ce346e2ef53b88d05e7ef99a880f398.less?modified=1329859860"  type="text/css"  rel="stylesheet" >

Again if I rename that file to 8ce346e2ef53b88d05e7ef99a880f398.css and link it manually, it works perfect.

Thanks again!

**Comment by bunchjesse** [comment]
Good catch. Fixed in v2.1.1, releasing today.
