### ISSUE TITLE
Solutions for Responsive stylesheets

### ISSUE THREAD

**Issue by moogaloo** [benwilkins/AutoMin#11]
I tend to use Malarkeys 320 and Up framework for handling device widths - it has the advantage of starting with smallest devices, often those with limited / slower data transfer and scales up from there. This way it only loads bigger images etc in bigger screen sizes where bandwidth is less of an iddue.

Full project details can be found here - http://stuffandnonsense.co.uk/projects/320andup/

Using the multiple stylesheets option, my head CSS looks something like:

```
<link type="text/css" media="screen, projection"href="/_assets/css/style.css">
<link rel="stylesheet" media="only screen and (min-width: 480px)" href="/_assets/css/480.css">
<link rel="stylesheet" media="only screen and (min-width: 600px)" href="/_assets/css/600.css">
<link rel="stylesheet" media="only screen and (min-width: 768px)" href="/_assets/css/768.css">
<link rel="stylesheet" media="only screen and (min-width: 992px)" href="/_assets/css/992.css">
```

as AutoMin requires you to specify the `media=""` as a parameter, the media screen and min widths become a problem... unless perhaps you wrap each and every line in its own AutoMin tag?

I tried putting all 5 above lines in 1 automin tag and it compresses the whole lot and kills any responsiveness.

I've tried compressing a CSS file that @imports the various css files using media queries but then Auto Mion doesnt compress them and they each get imported separately, defeating the purpose.

If I pull all the code for each of teh 5 css files into 1 css file and minify that, I end up with an unworkably large file.

This page - http://dev.vanilla.in-the-safe-hands-of-moogaloo.com/elements/ - shows roughly what is happening to the 5 css files that are being minified all together in one AutoMin tag pair.

To compare, http://local.oxyfire.com/whats-new/well-its-my-last-day-at-oxyfire-before-the-chrimbo-break/ is a site based on teh same rough files - different content, but you can see how the page should scale down with browser resizing.

As AutoMin removes this media query min-width rules, it just shows the full width view regardless of actual browser width.

Is the option here to just minify each css file in it's own AutoMin tag pair with it's own media rules? Seems a bit clunky to me...

**Comment by moogaloo** [comment]
actual template code:

{exp:automin:css 
    attribute:type="text/css" 
    attribute:title="default" 
    attribute:rel="stylesheet" 
}

&lt;link type="text/css" media="screen, projection" rel="stylesheet" title="default" href="/_assets/css/style.css">

&lt;link rel="stylesheet" media="only screen and (min-width: 480px)" href="/_assets/css/480.css">
&lt;link rel="stylesheet" media="only screen and (min-width: 600px)" href="/_assets/css/600.css">
&lt;link rel="stylesheet" media="only screen and (min-width: 768px)" href="/_assets/css/768.css">
&lt;link rel="stylesheet" media="only screen and (min-width: 992px)" href="/_assets/css/992.css">

&lt;link rel="stylesheet" href="/_assets/css/fb.css">

{/exp:automin:css}

---

this create the following link in the HTML page head:

&lt;link href="http://local.vanilla.com/_assets/automin/d171662daa047b50794256f6ab6a0918.css?modified=1331820629"  type="text/css"  title="default"  rel="stylesheet" >

(in my local setup - it's the correct domain for whatever environment I'm in, so:

&lt;link href="http://dev.vanilla.in-the-safe-hands-of-moogaloo.com/_assets/automin/d171662daa047b50794256f6ab6a0918.css?modified=1331827829"  type="text/css"  title="default"  rel="stylesheet" >

it's not putting the media="screen" etc in the cached file as it's not specified in the AutoMin tag pair.
In the print file I have specified it and it appears in the output HTML.

It's this media info that i need intact for the responsive functionality which is why I'm thinking i need to wrap each of the 4-5 lines in their own AutoMin tag pair.

**Comment by bunchjesse** [comment]
I see. That's an interesting use case. I've only ever seen media queries used _inside_ the stylesheet. I guess for now, you could open up those style sheets and add the media query to the top, enclosing all your CSS rules. I'll take a look at this more deeply when I address the next version of AutoMin. It won't be a high priority, however, since there is a valid workaround.

**Comment by moogaloo** [comment]
As in paste all 5-6 stylesheets into just one, use media queries within those stylesheets to break up the styles by device width, and the minify the whole sheet?

I think I tried that, but ant remember why I didn't stick with it... will give it another go and see what happens.

**Comment by bunchjesse** [comment]
No just add the respective media query to each file. AutoMin will combine them for you. Make sense?

**Comment by moogaloo** [comment]
oh right... so the browser will still download 5-6 individual css files but I've wrapped the contents of each in it's respective @media query.

**Comment by moogaloo** [comment]
yep - looks like it works perfectly - thanks for the help :)

**Comment by bunchjesse** [comment]
"oh right... so the browser will still download 5-6 individual css files but I've wrapped the contents of each in it's respective @media query." - No, AutoMin will combine and compress them into one cache file, but the media queries will be intact.

"yep - looks like it works perfectly - thanks for the help :)" - No problem. Glad you got it working.
