### ISSUE TITLE
Not all java has been compressed

### ISSUE THREAD

**Issue by gfive** [benwilkins/AutoMin#14]
I Updated Automin from 2.0 to 2.1.1
(removed the hooks and so on, and to be sure. Deinstalled and installed again)
After changing Tag attributes to the new version,
CSS is compressing like a charm, as always.
JS: Some will and some won’t combine/compress. When using 2.0 the same files compressed just fine.
Same for relative paths, the compressed js works for two segments in the url (domain.com/site/example
but not on the third or more like domain.com/site/example/tags/tag than the js stops working
What has changed?
What could I do, except downgrading to version 2.0

Kind regards,
Martijn

**Comment by bunchjesse** [comment]
Maybe clear your template cache?

**Comment by gfive** [comment]
Hello,
Also tried that, no luck.

Hmm Guess I will downgrade to 2.0... now hope that I find that version on my comp :-)

**Comment by gfive** [comment]
I noticed that I had version 1.3.1 working not 2.0.
Hope there will be a fix soon.

**Comment by bunchjesse** [comment]
Can you paste in the contents of your `exp:automin:js` tag(s)? I want to see what you're sending it.

**Comment by gfive** [comment]
As it is now, with AutoMin 2.0 (compresses/combine all as should be)

{exp:automin:js type="text/javascript"}

<script type="text/javascript" src="/static/members/js/jquery-1.7.1.min.js"></script>

{/exp:automin:js}

{exp:automin:js type="text/javascript"}

<script type="text/javascript" src="/static/members/js/src/jquery.event.wheel-1.0.js"></script>

<script type="text/javascript" src="/static/members/js/src/sizzle.js"></script>

<script type="text/javascript" src="/static/members/js/src/dateinput/dateinput.js"></script>

<script type="text/javascript" src="/static/members/js/src/overlay/overlay.js"></script>

<script type="text/javascript" src="/static/members/js/src/overlay/overlay.apple.js"></script>

<script type="text/javascript" src="/static/members/js/src/rangeinput/rangeinput.js"></script>

<script type="text/javascript" src="/static/members/js/src/scrollable/scrollable.js"></script>

<script type="text/javascript" src="/static/members/js/src/scrollable/scrollable.autoscroll.js"></script>

<script type="text/javascript" src="/static/members/js/src/scrollable/scrollable.navigator.js"></script>

<script type="text/javascript" src="/static/members/js/src/tabs/tabs.js"></script>

<script type="text/javascript" src="/static/members/js/src/tabs/tabs.slideshow.js"></script>

<script type="text/javascript" src="/static/members/js/src/tooltip/tooltip.js"></script>

<script type="text/javascript" src="/static/members/js/src/tooltip/tooltip.slide.js"></script>

<script type="text/javascript" src="/static/members/js/src/tooltip/tooltip.dynamic.js"></script>

<script type="text/javascript" src="/static/members/js/src/toolbox/toolbox.expose.js"></script>

<script type="text/javascript" src="/static/members/js/src/toolbox/toolbox.flashembed.js"></script>

<script type="text/javascript" src="/static/members/js/src/toolbox/toolbox.history.js"></script>

<script type="text/javascript" src="/static/members/js/src/toolbox/toolbox.mousewheel.js"></script>

<script type="text/javascript" src="/static/members/js/src/validator/validator.js"></script>

<script type="text/javascript" src="/static/members/js/src/jquery.event.drag.min.js"></script>

<script type="text/javascript" src="/static/members/js/src/jquery.event.drop.min.js"></script>

{/exp:automin:js}

{exp:automin:js type="text/javascript"}

<script type="text/javascript" src="/static/members/js/jquery.tip.js"></script>

<script type="text/javascript" src="/static/members/js/searchField.js"></script>

<script type="text/javascript" src="/static/members/js/jTour.min.js"></script>

<script type="text/javascript" src="/static/members/js/standard.js"></script>

<script type="text/javascript" src="/static/members/js/jquery.easing.js"></script>

{/exp:automin:js}

{if segment_1 == "help" }
{exp:automin:js type="text/javascript"}

<script type="text/javascript" src="/static/members/js/common.js"></script>

<script type="text/javascript" src="/static/members/js/jquery.accessibleList.js"></script>

{/exp:automin:js}
{/if}





{exp:automin:js type="text/javascript"}

<script type="text/javascript" src="/static/members/js/jquery.cookie.js"></script>

<script type="text/javascript" src="/static/members/js/jquery.ui.min.js"></script>

<script type="text/javascript" src="/static/members/js/jquery.tables.js"></script>

<script type="text/javascript" src="/static/members/js/jquery.flot.js"></script>

<script type="text/javascript" src="/static/members/js/global.js"></script>

<script type="text/javascript" src="/static/members/js/snip.js"></script>

<script type="text/javascript" src="/static/members/js/AquaGauge.js"></script>

{/exp:automin:js}

**Comment by bunchjesse** [comment]
And none of this works with 2.1.1? Do you have a test environment that I could access with 2.1.1 installed?

**Comment by gfive** [comment]
Pieces of the list I mailed you will combine/compress in 2.1.1

of the 6 blocks of javascript about 3 will compress/combine, others just show the java code like

<script type="text/javascript" src="/static/members/js/src/jquery.event.wheel-1.0.js"></script>


Sorry I don't have a test setup, just downgraded from 2.1.1 to 2.0
Working an a live server but EE turned off...

**Comment by gfive** [comment]
Not sure if you have time, but I could upgrade again (pfff :-) )

Some tech specs:
Running Mac Os X 10.7.3 Server (production webserver)
php 5.3.8
EE 2.4

AutoMin files are written to folder and requested from URL, example:
Path: /home/example/public_html/static/core
Url: http://static.example.com/core

**Comment by bunchjesse** [comment]
Sounds like AutoMin is running into an error and is returning your original javascript tags for safety. There should be an error in your template debugger that says what happened.

When you get a chance, please upgrade AutoMin again and turn template debugging on in EE. Then copy the template log and paste it here.

**Comment by gfive** [comment]
I will, thanks.
(due to the time difference I think it will be tomorrow that I will upgrade to 2.1.1)

**Comment by bunchjesse** [comment]
Closing this due to no response. Please submit a new issue if this persists.
