### ISSUE TITLE
Old versions?

### ISSUE THREAD

**Issue by ss5** [benwilkins/AutoMin#16]
Hi,
I am having huge problems after upgrading.
Scripts are messed up/https not  longer working.
Where can I find previous versions of Automin so I can downgrade?
Thnx

**Comment by bunchjesse** [comment]
Sorry to her that. You can find version snapshots by downloading on of the Github "tags". 

I would recommend reading the updated read me to make sure you're doing everything correctly. Also see the troubleshooting section for ideas.

**Comment by ss5** [comment]
Ahh.. how could I miss those?
Thnx
