### ISSUE TITLE
Doesn't appear in module list

### ISSUE THREAD

**Issue by jeremypeters** [benwilkins/AutoMin#17]
Hi.

I've added the Automin folder to my /system/expressionengine/third_party directory, but the module does not show up in my add-ons/modules list . Every other add-on I've installed is fine. Would you have any ideas what may  be causing this issue?

Many thanks.

**Comment by bunchjesse** [comment]
What version of EE are you using?

**Comment by jeremypeters** [comment]
Apologies - should have give you a bit more info.

EEv2.5.2

**Comment by bunchjesse** [comment]
I'll do some testing later this evening and get back to you. Hang tight.

**Comment by jeremypeters** [comment]
Great stuff, many thanks.

**Comment by bunchjesse** [comment]
Hey Jeremy, sorry for the delay. After a installing a fresh copy of EE 2.5.2, I was able to see it in the modules list. You might have some conflict with another extension. If you turn on debug mode by editing the admin.php file do you see any issues reported?

Screenshot: http://cl.ly/image/06323d460V1j

**Comment by mmeeksfamilyden** [comment]
Make sure the directory name is "automin". If it's not that exactly, it won't show up.

**Comment by jeremypeters** [comment]
Apologies for the late reply. Many thanks for the suggestions, but I have gone with a different solution.
