### ISSUE TITLE
Unable to load the requested class: automin_caching_library

### ISSUE THREAD

**Issue by picoallen** [benwilkins/AutoMin#18]
Hi,

I just upgraded to version 2.1.1 and am now getting the error "Unable to load the requested class: automin_caching_library"

I'm running EE v2.5.2 - Build Date: 20120606

In the libraries folder there is a file called caching_library, but not one called automin_caching_library.

Thanks

**Comment by bunchjesse** [comment]
Thanks for reporting this. Very sorry for the inconvenience. It seems that a recent pull request wasn't vetted enough. My bad. Please download and update to the 2.1.2 tag where I've fixed this and tested with the latest version of EE.

You can download 2.1.2 directly here: https://github.com/bunchjesse/AutoMin/zipball/v2.1.2

Thanks
