### ISSUE TITLE
LESS: error using Twitter Bootstrap 2.2.1

### ISSUE THREAD

**Issue by ginkelb** [benwilkins/AutoMin#23]
Hi There,

when trying to compile the bootstrap.less from the twitter bootstrap 2.2.1 i get the following error.

parse error: failed at `(~".span@{index}") { .span(@index); }` line: 1015

Googling the error message point to a post in the lessphp github issues
https://github.com/leafo/lessphp/issues/208

The solution they employed was to upgrade to lessphp 0.3.5 or higher. Going through your code i see your using lessphp version 0.3.1.

This is the extend my coding skills go, would it be possible for you to upgrade the lessphp version? Would be very very sweet to be able to adjust the colors of the site without having to manually recomplile the less and upload the css files.

With kind regard,
Bas van Ginkel

**Comment by bunchjesse** [comment]
Absolutely. I'll check it out this weekend.

**Comment by bunchjesse** [comment]
Hey Bas,

Please download the latest commit and let me know if that fixes your issues.

Thanks!

**Comment by ginkelb** [comment]
Thanks,

works like a charm now.

Met vriendelijke groet,
Bas van Ginkel
Bas van Ginkel
Ik help MKB bedrijven internet begrijpen en gebruiken
030 8200 271 | 06 29 51 69 00
http://www.ivyone.nl | bas@ivyone.nl
Grebbeberglaan 15, 3527VX Utrecht (routebeschrijving)
Twitter : @ivyone | Linkedin : basvanginkel

Op 26 nov. 2012, om 16:15 heeft Jesse Bunch notifications@github.com het volgende geschreven:
