### ISSUE TITLE
Automin files aren't gzipped

### ISSUE THREAD

**Issue by dankingsley** [benwilkins/AutoMin#28]
Hi,

Even though I have gzip compression turned on within expressionengine, the files generated by automin aren't gzipped. Is there a way to make them compressed?

Thanks,
Dan

**Comment by bunchjesse** [comment]
Dan, I wouldn't use ExpressionEngine's gzip feature. Gzip compression needs to be something done by your server prior to sending your web page's content to the browser. Here's how to enable it on apache web servers: http://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/
