### ISSUE TITLE
Multi Site Compatibility

### ISSUE THREAD

**Issue by ghost** [benwilkins/AutoMin#6]
Hello,

It seems that when I change a setting on one of my sites it globally changes the settings.  Your plugin on devotee shows it is multi site compatible.  Any chance this can be updated so the settings for Automin can be unique to each site?

**Comment by bunchjesse** [comment]
Yes, this is a bug. I will get a fix out shortly.

**Comment by ghost** [comment]
Thanks!  Love the plugin.  Have it working in one of my sites and I see a noticeable difference in page load time.

**Comment by jimjamdev** [comment]
Any luck?

**Comment by bunchjesse** [comment]
Not yet. I've been a bit swamped as of late and am currently on vacation. I'll try to get something rolled out ASAP, but it'll probably be late next week. Thanks for your patience!

**Comment by bunchjesse** [comment]
This has been fixed in v2.1 (commit f40d67ba7d4c61f5a8c566cf1c53f49cbf1001ee) which will be released this evening. Thanks for your patience!
