### ISSUE TITLE
LESS doesn't parse @import files

### ISSUE THREAD

**Issue by jmcgaha** [benwilkins/AutoMin#8]
I'm trying to use the LESS files from the Twitter Bootstrap (http://twitter.github.com/bootstrap/).

It has a bootstrap.less file which lists a bunch of less files to compile together like: @import "variables.less" @import "type.less"

AutoMin correctly will parse any LESS tags inside this file, but it doesn't parse and merge the @import statements to make one CSS file like other LESS tools that I've used

**Comment by bunchjesse** [comment]
Interesting. Thanks for reporting this. I'll check it out.

**Comment by bunchjesse** [comment]
Hey Everyone, I've confirmed that this is a bug. Unfortunately, this is going to take a bit longer for me to fix. Hold off on bootstrap or @imports (in your less files) for now. I'll have a fix to you ASAP. Thanks for your patience.

**Comment by bunchjesse** [comment]
This has been fixed in v2.1 (commit f40d67ba7d4c61f5a8c566cf1c53f49cbf1001ee) which will be released this evening. Thanks for your patience!
