### ISSUE TITLE
Minifying JS files breaks JS

### ISSUE THREAD

**Issue by chadcrowell** [benwilkins/AutoMin#9]
This also happens with Minimee on my ExpressionEngine site - so I am quite sure its something about the jquery plugins I am trying to minify, but they are standard stuff like cycle, jq tools, colorbox, cookie, etc. So I figure they are written well. If that is the case, why would they break when minified? I have 12 total files I am trying to minify, and only 6 of them can be minified. The other 6, if included in the Automin code, break the site's JS.

Thanks
Chad

**Comment by bunchjesse** [comment]
Hey Chad,

I'm working on AutoMin this evening. I'll get back with you in a bit.

**Comment by bunchjesse** [comment]
Chad,

Here are some things to try:
- Update to v2.1.1
- Try to narrow the problem down to one script if you can. Add only one script to AutoMin at a time to see which one breaks your setup.
- Run your JS through jslint. If you get any errors, you'll need to investigate further.

Let me know if any of those things help.

**Comment by bunchjesse** [comment]
Chad,

Any word on this? If not, I'm going to close this issue.

**Comment by chadcrowell** [comment]
Hi Jesse - very sorry for the delay. I had already done your point #2 and I have it working for some of the scripts, but adding in any of the others breaks the JS. I'll do the other 2 points and see what happens.

**Comment by bunchjesse** [comment]
Closing this due to no response. Please submit a new issue if the issue persists.
